version: '3.3'
services:
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    ports:
      - "6433:1433"
    environment:
      SA_PASSWORD: "PortalSQL01Demo#"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S db1.internal.prod.example.com -U SA -P 'Pa$$w0rd' -Q 'select distinct 1 from AdventureWorksDW2017.dbo.DimDate'
    networks:
      mynetwork:
        aliases:
          - db1.internal.prod.example.com
networks:
  mynetwork:
    driver: bridge